"""Post-backtest strategy validation, stress, and anti-overfit reporting."""

from __future__ import annotations

import csv
import html
import json
import os
from collections import Counter
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Final
from uuid import uuid4
from zoneinfo import ZoneInfo

import yaml

from neo_trader.runtime import get_runtime_commit_hash

BPS_FACTOR: Final = Decimal("10000")
DEFAULT_SPREAD_PENALTY_BPS: Final = {
    "tight": Decimal("1"),
    "normal": Decimal("5"),
    "wide": Decimal("15"),
}
CRYPTO_MARKERS: Final = (
    "btc",
    "bitcoin",
    "eth",
    "ethereum",
    "sol",
    "solana",
    "xrp",
    "ripple",
    "trx",
    "tron",
)


@dataclass(frozen=True)
class ValidationTrade:
    """One closed trade parsed from research backtest CSV."""

    instrument: str
    instrument_uid: str
    side: str
    entry_time: datetime
    exit_time: datetime
    quantity: Decimal
    entry_price: Decimal
    exit_price: Decimal
    pnl: Decimal
    mae: Decimal
    mfe: Decimal
    entry_slippage_bps: Decimal
    exit_slippage_bps: Decimal
    entry_spread_regime: str
    entry_volatility_regime: str
    entry_reason_codes: tuple[str, ...]
    exit_reason_codes: tuple[str, ...]


@dataclass(frozen=True)
class ValidationArtifacts:
    """Files generated by validation."""

    json_path: Path
    csv_path: Path
    html_path: Path
    next_universe_path: Path


@dataclass(frozen=True)
class StrategyValidationResult:
    """Validation result summary and artifacts."""

    or_verdict: str
    simple_verdict: str
    best_instruments: tuple[str, ...]
    disabled_instruments: tuple[str, ...]
    artifacts: ValidationArtifacts
    payload: Mapping[str, object]


ScenarioInput = tuple[ValidationTrade, ...] | tuple[tuple[ValidationTrade, Decimal], ...]


def validate_strategy_reports(
    *,
    liquidity_report_path: Path,
    or_report_path: Path,
    or_trades_csv_path: Path,
    simple_report_path: Path,
    simple_trades_csv_path: Path,
    reports_dir: Path = Path("data/reports"),
    neoassets_config_path: Path = Path("configs/neoassets_universe.yaml"),
    active_universe_next_path: Path = Path("configs/active_universe_next.yaml"),
    generated_at: datetime | None = None,
) -> StrategyValidationResult:
    """Validate latest strategy reports and write JSON/CSV/HTML artifacts."""

    timestamp = _as_utc(generated_at or datetime.now(UTC))
    liquidity_report = _load_json(liquidity_report_path)
    or_report = _load_json(or_report_path)
    simple_report = _load_json(simple_report_path)
    or_trades = read_trades_csv(or_trades_csv_path)
    simple_trades = read_trades_csv(simple_trades_csv_path)
    metadata = _load_neoasset_metadata(neoassets_config_path)

    timezone = ZoneInfo(_session_timezone(or_report) or _session_timezone(simple_report))
    or_summary = _strategy_summary(
        strategy_name="opening_range_book_momentum",
        report=or_report,
        trades=or_trades,
        timezone=timezone,
        metadata=metadata,
    )
    simple_summary = _strategy_summary(
        strategy_name="simple_book_momentum_research",
        report=simple_report,
        trades=simple_trades,
        timezone=timezone,
        metadata=metadata,
    )

    liquidity_by_ticker = _liquidity_by_ticker(liquidity_report)
    next_universe = _build_next_universe(
        metadata=metadata,
        liquidity_by_ticker=liquidity_by_ticker,
        or_summary=or_summary,
        simple_summary=simple_summary,
        generated_at=timestamp,
        active_universe_next_path=active_universe_next_path,
    )

    or_verdict = _or_verdict(or_summary)
    simple_verdict = _simple_verdict(simple_report, simple_summary)
    next_instruments = tuple(
        item
        for item in _sequence(_mapping(next_universe).get("instruments"))
        if isinstance(item, Mapping)
    )
    best_instruments = tuple(
        _string(item.get("ticker")) for item in next_instruments if item.get("enabled") is True
    )
    disabled_instruments = tuple(
        _string(item.get("ticker"))
        for item in next_instruments
        if item.get("enabled") is not True
    )

    payload: dict[str, object] = {
        "generated_at": timestamp.isoformat(),
        "commit_hash": get_runtime_commit_hash(),
        "source_reports": {
            "liquidity_report": str(liquidity_report_path),
            "or_report": str(or_report_path),
            "or_trades_csv": str(or_trades_csv_path),
            "simple_report": str(simple_report_path),
            "simple_trades_csv": str(simple_trades_csv_path),
        },
        "verdicts": {
            "opening_range_book_momentum": or_verdict,
            "simple_book_momentum_research": simple_verdict,
        },
        "strategies": {
            "opening_range_book_momentum": or_summary,
            "simple_book_momentum_research": simple_summary,
        },
        "next_universe": next_universe,
    }

    reports_dir.mkdir(parents=True, exist_ok=True)
    suffix = timestamp.strftime("%Y%m%d_%H%M%S")
    json_path = reports_dir / f"strategy_validation_{suffix}.json"
    csv_path = reports_dir / f"strategy_validation_{suffix}.csv"
    html_path = reports_dir / f"strategy_validation_{suffix}.html"
    _atomic_write_json(json_path, payload)
    _atomic_write_csv(csv_path, _validation_csv_rows(payload))
    _atomic_write_html(html_path, _validation_html(payload))
    _atomic_write_yaml(active_universe_next_path, next_universe)

    return StrategyValidationResult(
        or_verdict=or_verdict,
        simple_verdict=simple_verdict,
        best_instruments=best_instruments,
        disabled_instruments=disabled_instruments,
        artifacts=ValidationArtifacts(
            json_path=json_path,
            csv_path=csv_path,
            html_path=html_path,
            next_universe_path=active_universe_next_path,
        ),
        payload=payload,
    )


def read_trades_csv(path: Path) -> tuple[ValidationTrade, ...]:
    """Read research backtest trades CSV."""

    with path.open(encoding="utf-8", newline="") as handle:
        return tuple(_trade_from_row(row) for row in csv.DictReader(handle))


def _strategy_summary(
    *,
    strategy_name: str,
    report: Mapping[str, object],
    trades: Sequence[ValidationTrade],
    timezone: ZoneInfo,
    metadata: Mapping[str, Mapping[str, object]],
) -> dict[str, object]:
    metrics = _metrics(trades, timezone=timezone)
    instrument_metrics = _instrument_metrics(trades)
    stress = _stress_tests(trades, metadata=metadata, timezone=timezone)
    anti_overfit = _anti_overfit_checks(trades, metrics=metrics, timezone=timezone)
    report_metrics = _mapping(report.get("metrics"))
    return {
        "strategy_name": strategy_name,
        "report_total_pnl": _string(report_metrics.get("total_pnl")),
        "report_profit_factor": _string(report_metrics.get("profit_factor")),
        "report_max_drawdown": _string(report_metrics.get("max_drawdown")),
        "metrics": metrics,
        "instrument_metrics": instrument_metrics,
        "stress_tests": stress,
        "anti_overfit": anti_overfit,
        "reject_reason_distribution": _int_mapping(
            report_metrics.get("reject_reason_distribution")
            or report_metrics.get("reason_code_distribution")
        ),
        "reason_code_distribution": _int_mapping(report_metrics.get("reason_code_distribution")),
    }


def _metrics(
    trades: Sequence[ValidationTrade],
    *,
    timezone: ZoneInfo,
) -> dict[str, object]:
    pnls = [trade.pnl for trade in trades]
    slippages = [
        value
        for trade in trades
        for value in (trade.entry_slippage_bps, trade.exit_slippage_bps)
    ]
    total_pnl = sum(pnls, Decimal("0"))
    return {
        "total_pnl": str(total_pnl),
        "trades": len(trades),
        "winrate": str(_winrate(pnls)),
        "profit_factor": _decimal_or_none_string(_profit_factor(pnls)),
        "average_trade": str(_average(pnls)),
        "average_r": _decimal_or_none_string(_average_r(trades)),
        "max_drawdown": str(_max_drawdown(trades)),
        "avg_slippage_bps": str(_average(slippages)),
        "max_slippage_bps": str(max(slippages) if slippages else Decimal("0")),
        "pnl_by_instrument": _decimal_mapping(_pnl_by(trades, lambda trade: trade.instrument)),
        "trades_by_instrument": dict(Counter(trade.instrument for trade in trades)),
        "winrate_by_instrument": _by_instrument_value(
            trades,
            lambda items: _winrate([trade.pnl for trade in items]),
        ),
        "profit_factor_by_instrument": _by_instrument_optional_value(
            trades,
            lambda items: _profit_factor([trade.pnl for trade in items]),
        ),
        "pnl_by_hour": _decimal_mapping(_pnl_by(trades, lambda trade: _hour_key(trade, timezone))),
        "pnl_by_spread_regime": _decimal_mapping(
            _pnl_by(trades, lambda trade: trade.entry_spread_regime or "unknown")
        ),
        "pnl_by_volatility_regime": _decimal_mapping(
            _pnl_by(trades, lambda trade: trade.entry_volatility_regime or "unknown")
        ),
    }


def _instrument_metrics(trades: Sequence[ValidationTrade]) -> dict[str, dict[str, object]]:
    result: dict[str, dict[str, object]] = {}
    for instrument in sorted({trade.instrument for trade in trades}):
        items = [trade for trade in trades if trade.instrument == instrument]
        pnls = [trade.pnl for trade in items]
        slippages = [
            value
            for trade in items
            for value in (trade.entry_slippage_bps, trade.exit_slippage_bps)
        ]
        result[instrument] = {
            "pnl": str(sum(pnls, Decimal("0"))),
            "trades": len(items),
            "winrate": str(_winrate(pnls)),
            "profit_factor": _decimal_or_none_string(_profit_factor(pnls)),
            "average_trade": str(_average(pnls)),
            "average_r": _decimal_or_none_string(_average_r(items)),
            "max_drawdown": str(_max_drawdown(items)),
            "avg_slippage_bps": str(_average(slippages)),
            "max_slippage_bps": str(max(slippages) if slippages else Decimal("0")),
        }
    return result


def _stress_tests(
    trades: Sequence[ValidationTrade],
    *,
    metadata: Mapping[str, Mapping[str, object]],
    timezone: ZoneInfo,
) -> dict[str, dict[str, object]]:
    best, worst = _best_worst_instruments(trades)
    scenarios: dict[str, ScenarioInput] = {
        "slippage_x1": tuple((trade, trade.pnl) for trade in trades),
        "slippage_x2": tuple(
            (trade, _slippage_stressed_pnl(trade, Decimal("2"))) for trade in trades
        ),
        "slippage_x3": tuple(
            (trade, _slippage_stressed_pnl(trade, Decimal("3"))) for trade in trades
        ),
        "spread_penalty_x1": tuple(
            (trade, _spread_penalty_pnl(trade, Decimal("1"))) for trade in trades
        ),
        "spread_penalty_x2": tuple(
            (trade, _spread_penalty_pnl(trade, Decimal("2"))) for trade in trades
        ),
        "remove_best_instrument": tuple(trade for trade in trades if trade.instrument != best),
        "remove_worst_instrument": tuple(trade for trade in trades if trade.instrument != worst),
        "only_crypto_neoassets": tuple(
            trade
            for trade in trades
            if _instrument_category(trade.instrument, metadata) == "crypto"
        ),
        "only_stock_neoassets": tuple(
            trade for trade in trades if _instrument_category(trade.instrument, metadata) == "stock"
        ),
    }
    return {
        name: _scenario_metrics(value, timezone=timezone)
        for name, value in scenarios.items()
    }


def _anti_overfit_checks(
    trades: Sequence[ValidationTrade],
    *,
    metrics: Mapping[str, object],
    timezone: ZoneInfo,
) -> dict[str, object]:
    first_half, second_half = _split_halves(trades)
    pnl_by_instrument = _decimal_dict(metrics.get("pnl_by_instrument"))
    pnl_by_hour = _decimal_dict(metrics.get("pnl_by_hour"))
    total_pnl = _decimal_from_string(metrics.get("total_pnl"))
    instrument_dependency = _dependency_ratio(pnl_by_instrument, total_pnl)
    hour_dependency = _dependency_ratio(pnl_by_hour, total_pnl)
    per_instrument = _instrument_metrics(trades)
    return {
        "first_half": _metrics(first_half, timezone=timezone),
        "second_half": _metrics(second_half, timezone=timezone),
        "per_instrument_stability": {
            instrument: {
                "trades": values["trades"],
                "pnl": values["pnl"],
                "winrate": values["winrate"],
                "stable": int(str(values.get("trades", 0))) >= 3
                and Decimal(str(values.get("pnl", "0"))) > 0,
            }
            for instrument, values in per_instrument.items()
        },
        "single_instrument_dependency_ratio": str(instrument_dependency),
        "single_hour_dependency_ratio": str(hour_dependency),
        "no_single_instrument_dependency": instrument_dependency <= Decimal("0.70"),
        "no_single_hour_dependency": hour_dependency <= Decimal("0.70"),
    }


def _build_next_universe(
    *,
    metadata: Mapping[str, Mapping[str, object]],
    liquidity_by_ticker: Mapping[str, Mapping[str, object]],
    or_summary: Mapping[str, object],
    simple_summary: Mapping[str, object],
    generated_at: datetime,
    active_universe_next_path: Path,
) -> dict[str, object]:
    rows: list[dict[str, object]] = []
    for ticker, raw_meta in sorted(metadata.items()):
        validation_score = _next_universe_score(
            ticker=ticker,
            liquidity_by_ticker=liquidity_by_ticker,
            or_summary=or_summary,
            simple_summary=simple_summary,
        )
        rows.append(
            {
                "ticker": ticker,
                "uid": _string(raw_meta.get("uid")),
                "enabled": False,
                "score": str(validation_score),
                "category": _instrument_category(ticker, metadata),
                "reason": "",
                "validation": {
                    "or_pnl": _instrument_pnl(or_summary, ticker),
                    "or_trades": _instrument_trades(or_summary, ticker),
                    "simple_pnl": _instrument_pnl(simple_summary, ticker),
                    "simple_trades": _instrument_trades(simple_summary, ticker),
                    "liquidity_score": str(
                        _optional_decimal(
                            _mapping(liquidity_by_ticker.get(ticker)).get("score")
                        )
                        or Decimal("0")
                    ),
                },
            }
        )
    rows.sort(key=lambda item: Decimal(str(item["score"])), reverse=True)
    enabled_tickers = {str(item["ticker"]) for item in rows[:3]}
    for row in rows:
        ticker = str(row["ticker"])
        row["enabled"] = ticker in enabled_tickers
        row["reason"] = (
            "top_3_validation_liquidity"
            if row["enabled"]
            else _disable_reason(ticker, or_summary, simple_summary, liquidity_by_ticker)
        )
    return {
        "generated_by": "neo_trader.research.strategy_validation",
        "generated_at": generated_at.isoformat(),
        "commit_hash": get_runtime_commit_hash(),
        "source": "Strategy Validation Sprint 1",
        "path": str(active_universe_next_path),
        "instruments": rows,
    }


def _next_universe_score(
    *,
    ticker: str,
    liquidity_by_ticker: Mapping[str, Mapping[str, object]],
    or_summary: Mapping[str, object],
    simple_summary: Mapping[str, object],
) -> Decimal:
    liquidity_score = _optional_decimal(_mapping(liquidity_by_ticker.get(ticker)).get("score"))
    score = liquidity_score or Decimal("0")
    or_pnl = Decimal(_instrument_pnl(or_summary, ticker))
    simple_pnl = Decimal(_instrument_pnl(simple_summary, ticker))
    or_trades = _instrument_trades(or_summary, ticker)
    simple_trades = _instrument_trades(simple_summary, ticker)
    if or_pnl > 0:
        score += Decimal("20")
    if simple_pnl > 0:
        score += Decimal("10")
    if or_trades >= 3:
        score += Decimal("5")
    if or_trades == 0 and simple_trades == 0:
        score -= Decimal("10")
    if or_pnl + simple_pnl < 0:
        score -= Decimal("20")
    return score


def _disable_reason(
    ticker: str,
    or_summary: Mapping[str, object],
    simple_summary: Mapping[str, object],
    liquidity_by_ticker: Mapping[str, Mapping[str, object]],
) -> str:
    combined_pnl = Decimal(_instrument_pnl(or_summary, ticker)) + Decimal(
        _instrument_pnl(simple_summary, ticker)
    )
    liquidity_score = _optional_decimal(_mapping(liquidity_by_ticker.get(ticker)).get("score"))
    if combined_pnl < 0:
        return "negative_validation_pnl"
    if liquidity_score is not None and liquidity_score < 0:
        return "weak_liquidity_score"
    if _instrument_trades(or_summary, ticker) == 0:
        return "no_or_trades"
    return "below_top3_validation_rank"


def _or_verdict(summary: Mapping[str, object]) -> str:
    metrics = _mapping(summary.get("metrics"))
    anti = _mapping(summary.get("anti_overfit"))
    trades = int(str(metrics.get("trades", 0)))
    total_pnl = _decimal_from_string(metrics.get("total_pnl"))
    profit_factor = _optional_decimal(metrics.get("profit_factor")) or Decimal("0")
    if trades < 30:
        return "needs more data"
    if total_pnl <= 0 or profit_factor <= Decimal("1"):
        return "reject"
    if (
        anti.get("no_single_instrument_dependency") is not True
        or anti.get("no_single_hour_dependency") is not True
    ):
        return "needs more data"
    first = _decimal_from_string(_mapping(anti.get("first_half")).get("total_pnl"))
    second = _decimal_from_string(_mapping(anti.get("second_half")).get("total_pnl"))
    if first <= 0 or second <= 0:
        return "needs more data"
    return "candidate"


def _simple_verdict(report: Mapping[str, object], summary: Mapping[str, object]) -> str:
    marker = _string(report.get("research_mode_marker"))
    if marker == "RESEARCH_ONLY_NOT_FOR_LIVE":
        return "diagnostic only"
    metrics = _mapping(summary.get("metrics"))
    if _decimal_from_string(metrics.get("total_pnl")) <= 0:
        return "reject"
    return "candidate"


def _scenario_metrics(value: ScenarioInput, *, timezone: ZoneInfo) -> dict[str, object]:
    if not value:
        return _metrics((), timezone=timezone)
    first = value[0]
    if isinstance(first, tuple):
        trades = [item[0] for item in value if isinstance(item, tuple)]
        stressed = [item[1] for item in value if isinstance(item, tuple)]
        return _metrics_with_pnls(trades, stressed, timezone=timezone)
    return _metrics(value, timezone=timezone)  # type: ignore[arg-type]


def _metrics_with_pnls(
    trades: Sequence[ValidationTrade],
    pnls: Sequence[Decimal],
    *,
    timezone: ZoneInfo,
) -> dict[str, object]:
    adjusted = [
        _trade_with_pnl(trade, pnl)
        for trade, pnl in zip(trades, pnls, strict=True)
    ]
    return _metrics(adjusted, timezone=timezone)


def _trade_with_pnl(trade: ValidationTrade, pnl: Decimal) -> ValidationTrade:
    return ValidationTrade(
        instrument=trade.instrument,
        instrument_uid=trade.instrument_uid,
        side=trade.side,
        entry_time=trade.entry_time,
        exit_time=trade.exit_time,
        quantity=trade.quantity,
        entry_price=trade.entry_price,
        exit_price=trade.exit_price,
        pnl=pnl,
        mae=trade.mae,
        mfe=trade.mfe,
        entry_slippage_bps=trade.entry_slippage_bps,
        exit_slippage_bps=trade.exit_slippage_bps,
        entry_spread_regime=trade.entry_spread_regime,
        entry_volatility_regime=trade.entry_volatility_regime,
        entry_reason_codes=trade.entry_reason_codes,
        exit_reason_codes=trade.exit_reason_codes,
    )


def _slippage_stressed_pnl(trade: ValidationTrade, multiplier: Decimal) -> Decimal:
    extra_multiplier = max(multiplier - Decimal("1"), Decimal("0"))
    extra_cost = (
        (abs(trade.entry_price) * trade.entry_slippage_bps)
        + (abs(trade.exit_price) * trade.exit_slippage_bps)
    ) * trade.quantity * extra_multiplier / BPS_FACTOR
    return trade.pnl - extra_cost


def _spread_penalty_pnl(trade: ValidationTrade, multiplier: Decimal) -> Decimal:
    spread_bps = DEFAULT_SPREAD_PENALTY_BPS.get(
        trade.entry_spread_regime,
        Decimal("8"),
    )
    cost = (
        (abs(trade.entry_price) + abs(trade.exit_price))
        * trade.quantity
        * spread_bps
        * multiplier
        / BPS_FACTOR
    )
    return trade.pnl - cost


def _best_worst_instruments(trades: Sequence[ValidationTrade]) -> tuple[str, str]:
    pnl_by_instrument = _pnl_by(trades, lambda trade: trade.instrument)
    if not pnl_by_instrument:
        return "", ""
    best = max(pnl_by_instrument, key=lambda item: pnl_by_instrument[item])
    worst = min(pnl_by_instrument, key=lambda item: pnl_by_instrument[item])
    return best, worst


def _split_halves(
    trades: Sequence[ValidationTrade],
) -> tuple[tuple[ValidationTrade, ...], tuple[ValidationTrade, ...]]:
    ordered = tuple(sorted(trades, key=lambda trade: trade.entry_time))
    if not ordered:
        return (), ()
    midpoint = ordered[0].entry_time + ((ordered[-1].entry_time - ordered[0].entry_time) / 2)
    first = tuple(trade for trade in ordered if trade.entry_time <= midpoint)
    second = tuple(trade for trade in ordered if trade.entry_time > midpoint)
    return first, second


def _dependency_ratio(values: Mapping[str, Decimal], total_pnl: Decimal) -> Decimal:
    if not values:
        return Decimal("0")
    positive_total = total_pnl if total_pnl > 0 else sum(
        value for value in values.values() if value > 0
    )
    if positive_total <= 0:
        return Decimal("1")
    return max((value for value in values.values()), default=Decimal("0")) / positive_total


def _instrument_category(
    ticker: str,
    metadata: Mapping[str, Mapping[str, object]],
) -> str:
    raw = _mapping(metadata.get(ticker))
    haystack = " ".join(
        _string(raw.get(key))
        for key in ("ticker", "name", "instrument_type", "class_code")
    ).lower()
    return "crypto" if any(marker in haystack for marker in CRYPTO_MARKERS) else "stock"


def _instrument_pnl(summary: Mapping[str, object], ticker: str) -> str:
    metrics = _mapping(summary.get("metrics"))
    pnl_by_instrument = _mapping(metrics.get("pnl_by_instrument"))
    return _string(pnl_by_instrument.get(ticker) or "0")


def _instrument_trades(summary: Mapping[str, object], ticker: str) -> int:
    metrics = _mapping(summary.get("metrics"))
    trades_by_instrument = _mapping(metrics.get("trades_by_instrument"))
    value = trades_by_instrument.get(ticker, 0)
    return int(str(value))


def _trade_from_row(row: Mapping[str, str]) -> ValidationTrade:
    return ValidationTrade(
        instrument=row["instrument"],
        instrument_uid=row["instrument_uid"],
        side=row["side"],
        entry_time=_parse_datetime(row["entry_time"]),
        exit_time=_parse_datetime(row["exit_time"]),
        quantity=_decimal(row["quantity"], "quantity"),
        entry_price=_decimal(row["entry_price"], "entry_price"),
        exit_price=_decimal(row["exit_price"], "exit_price"),
        pnl=_decimal(row["pnl"], "pnl"),
        mae=_decimal(row["mae"], "mae"),
        mfe=_decimal(row["mfe"], "mfe"),
        entry_slippage_bps=_decimal(row["entry_slippage_bps"], "entry_slippage_bps"),
        exit_slippage_bps=_decimal(row["exit_slippage_bps"], "exit_slippage_bps"),
        entry_spread_regime=row.get("entry_spread_regime", "unknown") or "unknown",
        entry_volatility_regime=row.get("entry_volatility_regime", "unknown") or "unknown",
        entry_reason_codes=_code_tuple(row.get("entry_reason_codes", "")),
        exit_reason_codes=_code_tuple(row.get("exit_reason_codes", "")),
    )


def _by_instrument_value(
    trades: Sequence[ValidationTrade],
    value_func: Callable[[Sequence[ValidationTrade]], Decimal],
) -> dict[str, str]:
    return {
        instrument: str(value_func([trade for trade in trades if trade.instrument == instrument]))
        for instrument in sorted({trade.instrument for trade in trades})
    }


def _by_instrument_optional_value(
    trades: Sequence[ValidationTrade],
    value_func: Callable[[Sequence[ValidationTrade]], Decimal | None],
) -> dict[str, str | None]:
    return {
        instrument: _decimal_or_none_string(
            value_func([trade for trade in trades if trade.instrument == instrument])
        )
        for instrument in sorted({trade.instrument for trade in trades})
    }


def _pnl_by(
    trades: Sequence[ValidationTrade],
    key_func: Callable[[ValidationTrade], str],
) -> dict[str, Decimal]:
    result: dict[str, Decimal] = {}
    for trade in trades:
        key = key_func(trade)
        result[key] = result.get(key, Decimal("0")) + trade.pnl
    return result


def _winrate(pnls: Sequence[Decimal]) -> Decimal:
    return Decimal(sum(1 for pnl in pnls if pnl > 0)) / Decimal(len(pnls)) if pnls else Decimal("0")


def _profit_factor(pnls: Sequence[Decimal]) -> Decimal | None:
    gross_profit = sum((pnl for pnl in pnls if pnl > 0), Decimal("0"))
    gross_loss = sum((pnl for pnl in pnls if pnl < 0), Decimal("0"))
    if gross_loss == 0:
        return None
    return gross_profit / abs(gross_loss)


def _average(values: Sequence[Decimal]) -> Decimal:
    return sum(values, Decimal("0")) / Decimal(len(values)) if values else Decimal("0")


def _average_r(trades: Sequence[ValidationTrade]) -> Decimal | None:
    values = [trade.pnl / abs(trade.mae) for trade in trades if trade.mae < 0]
    return _average(values) if values else None


def _max_drawdown(trades: Sequence[ValidationTrade]) -> Decimal:
    equity = Decimal("0")
    peak = Decimal("0")
    max_drawdown = Decimal("0")
    for trade in sorted(trades, key=lambda item: item.exit_time):
        equity += trade.pnl
        peak = max(peak, equity)
        max_drawdown = max(max_drawdown, peak - equity)
    return max_drawdown


def _hour_key(trade: ValidationTrade, timezone: ZoneInfo) -> str:
    return f"{_as_utc(trade.entry_time).astimezone(timezone).hour:02d}"


def _load_json(path: Path) -> Mapping[str, object]:
    loaded = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(loaded, Mapping):
        raise ValueError(f"JSON root must be a mapping: {path}")
    return loaded


def _load_neoasset_metadata(path: Path) -> dict[str, Mapping[str, object]]:
    if not path.exists():
        return {}
    loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(loaded, Mapping):
        return {}
    instruments = loaded.get("instruments")
    if not isinstance(instruments, Sequence) or isinstance(instruments, str | bytes):
        return {}
    result: dict[str, Mapping[str, object]] = {}
    for item in instruments:
        if isinstance(item, Mapping):
            ticker = _string(item.get("ticker"))
            if ticker:
                result[ticker] = {str(key): value for key, value in item.items()}
    return result


def _liquidity_by_ticker(report: Mapping[str, object]) -> dict[str, Mapping[str, object]]:
    rows = report.get("ranked_universe")
    if not isinstance(rows, Sequence) or isinstance(rows, str | bytes):
        return {}
    result: dict[str, Mapping[str, object]] = {}
    for item in rows:
        if isinstance(item, Mapping):
            ticker = _string(item.get("ticker"))
            if ticker:
                result[ticker] = {str(key): value for key, value in item.items()}
    return result


def _session_timezone(report: Mapping[str, object]) -> str:
    session = _mapping(report.get("session"))
    value = _string(session.get("timezone"))
    return value or "Europe/Moscow"


def _validation_csv_rows(payload: Mapping[str, object]) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    strategies = _mapping(payload.get("strategies"))
    for strategy_name, strategy_value in strategies.items():
        strategy = _mapping(strategy_value)
        metrics = _mapping(strategy.get("metrics"))
        rows.append(
            {
                "section": "strategy",
                "strategy": strategy_name,
                "name": "summary",
                "trades": metrics.get("trades", 0),
                "total_pnl": metrics.get("total_pnl", "0"),
                "profit_factor": metrics.get("profit_factor"),
                "max_drawdown": metrics.get("max_drawdown", "0"),
                "winrate": metrics.get("winrate", "0"),
            }
        )
        for instrument, values in _mapping(strategy.get("instrument_metrics")).items():
            row: dict[str, object] = {
                "section": "instrument",
                "strategy": strategy_name,
                "name": str(instrument),
            }
            row.update(_mapping(values))
            rows.append(row)
        for scenario, values in _mapping(strategy.get("stress_tests")).items():
            scenario_metrics = _mapping(values)
            rows.append(
                {
                    "section": "stress",
                    "strategy": strategy_name,
                    "name": scenario,
                    "trades": scenario_metrics.get("trades", 0),
                    "total_pnl": scenario_metrics.get("total_pnl", "0"),
                    "profit_factor": scenario_metrics.get("profit_factor"),
                    "max_drawdown": scenario_metrics.get("max_drawdown", "0"),
                    "winrate": scenario_metrics.get("winrate", "0"),
                }
            )
    for item in _sequence(_mapping(payload.get("next_universe")).get("instruments")):
        if isinstance(item, Mapping):
            rows.append(
                {
                    "section": "next_universe",
                    "strategy": "",
                    "name": item.get("ticker", ""),
                    "enabled": item.get("enabled", False),
                    "score": item.get("score", "0"),
                    "reason": item.get("reason", ""),
                }
            )
    return rows


def _validation_html(payload: Mapping[str, object]) -> str:
    verdicts = _mapping(payload.get("verdicts"))
    next_universe = _mapping(payload.get("next_universe"))
    strategies = _mapping(payload.get("strategies"))
    summary_rows = [
        (strategy, verdicts.get(strategy, ""))
        for strategy in sorted(verdicts)
    ]
    universe_rows = [
        (
            _string(item.get("ticker")),
            _string(item.get("enabled")),
            _string(item.get("score")),
            _string(item.get("reason")),
        )
        for item in _sequence(next_universe.get("instruments"))
        if isinstance(item, Mapping)
    ]
    stress_rows: list[tuple[str, str, str, str]] = []
    for strategy_name, strategy_value in strategies.items():
        stress = _mapping(_mapping(strategy_value).get("stress_tests"))
        for name, values in stress.items():
            metrics = _mapping(values)
            stress_rows.append(
                (
                    str(strategy_name),
                    str(name),
                    _string(metrics.get("total_pnl")),
                    _string(metrics.get("profit_factor")),
                )
            )
    return (
        "<!doctype html><html><head><meta charset=\"utf-8\">"
        "<title>NeoIntraday strategy validation</title>"
        "<style>body{font-family:Arial,sans-serif;margin:24px;color:#17202a;}"
        "table{border-collapse:collapse;margin:12px 0 24px;width:100%;}"
        "th,td{border:1px solid #d5d8dc;padding:6px 8px;text-align:left;}"
        "th{background:#f4f6f7;}</style></head><body>"
        "<h1>NeoIntraday strategy validation</h1>"
        f"<p>commit_hash: {html.escape(_string(payload.get('commit_hash')))}</p>"
        "<h2>Verdicts</h2>"
        f"{_html_table(('Strategy', 'Verdict'), summary_rows)}"
        "<h2>Stress Tests</h2>"
        f"{_html_table(('Strategy', 'Scenario', 'Total PnL', 'Profit Factor'), stress_rows)}"
        "<h2>Next Universe</h2>"
        f"{_html_table(('Ticker', 'Enabled', 'Score', 'Reason'), universe_rows)}"
        "</body></html>\n"
    )


def _html_table(headers: Sequence[str], rows: Sequence[Sequence[object]]) -> str:
    header_html = "".join(f"<th>{html.escape(str(item))}</th>" for item in headers)
    rows_html = "".join(
        "<tr>" + "".join(f"<td>{html.escape(str(value))}</td>" for value in row) + "</tr>"
        for row in rows
    )
    return f"<table><thead><tr>{header_html}</tr></thead><tbody>{rows_html}</tbody></table>"


def _atomic_write_json(path: Path, payload: Mapping[str, object]) -> None:
    _atomic_write_text(path, json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))


def _atomic_write_csv(path: Path, rows: Sequence[Mapping[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_name(f".{path.name}.{uuid4().hex}.tmp")
    fieldnames = sorted({key for row in rows for key in row})
    try:
        with tmp_path.open("w", encoding="utf-8", newline="") as handle:
            writer = csv.DictWriter(handle, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(rows)
        os.replace(tmp_path, path)
    finally:
        if tmp_path.exists():
            tmp_path.unlink()


def _atomic_write_html(path: Path, document: str) -> None:
    _atomic_write_text(path, document)


def _atomic_write_yaml(path: Path, payload: Mapping[str, object]) -> None:
    _atomic_write_text(path, yaml.safe_dump(payload, sort_keys=False, allow_unicode=True))


def _atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_name(f".{path.name}.{uuid4().hex}.tmp")
    try:
        tmp_path.write_text(text, encoding="utf-8")
        os.replace(tmp_path, path)
    finally:
        if tmp_path.exists():
            tmp_path.unlink()


def _int_mapping(value: object) -> dict[str, int]:
    mapping = _mapping(value)
    result: dict[str, int] = {}
    for key, item in mapping.items():
        try:
            result[str(key)] = int(str(item))
        except ValueError:
            continue
    return result


def _decimal_mapping(values: Mapping[str, Decimal]) -> dict[str, str]:
    return {key: str(value) for key, value in sorted(values.items())}


def _decimal_dict(value: object) -> dict[str, Decimal]:
    return {
        key: _decimal_from_string(item)
        for key, item in _mapping(value).items()
    }


def _mapping(value: object) -> Mapping[str, object]:
    return value if isinstance(value, Mapping) else {}


def _sequence(value: object) -> tuple[object, ...]:
    if isinstance(value, Sequence) and not isinstance(value, str | bytes | bytearray):
        return tuple(value)
    return ()


def _code_tuple(value: str) -> tuple[str, ...]:
    return tuple(item for item in value.split("|") if item)


def _parse_datetime(value: str) -> datetime:
    return _as_utc(datetime.fromisoformat(value.replace("Z", "+00:00")))


def _optional_decimal(value: object) -> Decimal | None:
    if value is None or isinstance(value, bool):
        return None
    try:
        if isinstance(value, Decimal):
            return value if value.is_finite() else None
        if isinstance(value, int | str):
            parsed = Decimal(value)
            return parsed if parsed.is_finite() else None
        if isinstance(value, float):
            parsed = Decimal(str(value))
            return parsed if parsed.is_finite() else None
    except (InvalidOperation, ValueError):
        return None
    return None


def _decimal(value: object, field_name: str) -> Decimal:
    parsed = _optional_decimal(value)
    if parsed is None:
        raise ValueError(f"{field_name} must be a finite decimal.")
    return parsed


def _decimal_from_string(value: object) -> Decimal:
    return _optional_decimal(value) or Decimal("0")


def _decimal_or_none_string(value: Decimal | None) -> str | None:
    return None if value is None else str(value)


def _string(value: object) -> str:
    return "" if value is None else str(value)


def _as_utc(value: datetime) -> datetime:
    if value.tzinfo is None:
        return value.replace(tzinfo=UTC)
    return value.astimezone(UTC)


__all__ = [
    "StrategyValidationResult",
    "ValidationArtifacts",
    "ValidationTrade",
    "read_trades_csv",
    "validate_strategy_reports",
]
