"""Golden market: literal expectations are intentionally not generated by production code."""

from __future__ import annotations

import json
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

import pyarrow as pa
import pytest

from neo_trader.neobitcoin_research.independent_oracle import validate_independent_oracle
from neo_trader.neobitcoin_research.schema_v4 import ExecutionConfig, FeatureConfig, RawOnlyPipeline

FIXTURE = Path(__file__).parent / "fixtures" / "schema_v4_golden_synthetic.json"


def _ts(value: str) -> datetime:
    return datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone(UTC)


def _sweep(levels: list[dict[str, float]], quantity: float) -> tuple[float, float]:
    remaining, filled, notional = quantity, 0.0, 0.0
    for level in levels:
        take = min(remaining, level["quantity"])
        filled += take
        notional += take * level["price"]
        remaining -= take
        if remaining == 0:
            break
    return filled, notional / filled


def _oracle(data: dict[str, Any], passive_timeout_seconds: float = 30.0) -> dict[str, Any]:
    """Small independent event-loop oracle, deliberately separate from materializer helpers."""
    t0 = _ts(data["candidate_start"])
    books = sorted(data["orderbook"], key=lambda row: _ts(row["exchange_ts"]))
    trades = sorted(data["trades"], key=lambda row: _ts(row["exchange_ts"]))
    feature = data["feature"]
    result: dict[str, Any] = {}
    signed = sum(
        (row["quantity"] if row["side"] == "BUY" else -row["quantity"])
        for row in trades
        if t0 - timedelta(seconds=10) < _ts(row["exchange_ts"]) <= t0
        and row["side"] in {"BUY", "SELL"}
    )
    result["trade_flow_10s"] = signed
    latest = max(
        [_ts(row["exchange_ts"]) for row in books + trades if _ts(row["exchange_ts"]) <= t0]
    )
    result["data_age_ms"] = (t0 - latest).total_seconds() * 1000
    delayed_book = next(
        row for row in books if _ts(row["exchange_ts"]) >= t0 + timedelta(milliseconds=100)
    )
    executions: dict[str, dict[str, Any]] = {}
    for side in ("LONG", "SHORT"):
        levels = delayed_book["asks" if side == "LONG" else "bids"]
        filled, price = _sweep(levels, 10.0)
        executions[f"{side}/aggressive_marketable"] = {
            "status": "FULL_FILL" if filled == 10 else "PARTIAL_FILL",
            "filled": filled,
            "remaining": 10.0 - filled,
            "fill_price": price,
            "delay_ms": 200,
        }
        touch = feature["best_ask" if side == "LONG" else "best_bid"]
        executions[f"{side}/ideal_touch"] = {
            "status": "FULL_FILL",
            "filled": 10.0,
            "remaining": 0.0,
            "fill_price": touch,
            "delay_ms": 0,
        }
        for model, placement_ms, queue in (
            ("passive_best", 0, 5.0),
            ("passive_conservative", 0, 20.0),
            ("passive_delayed", 500, 5.0),
        ):
            order_price = feature["best_bid" if side == "LONG" else "best_ask"]
            wanted_trade_side = "SELL" if side == "LONG" else "BUY"
            filled, fill_at = 0.0, None
            placement = t0 + timedelta(milliseconds=placement_ms)
            for trade in trades:
                event_ts = _ts(trade["exchange_ts"])
                crossed = (
                    trade["price"] <= order_price
                    if side == "LONG"
                    else trade["price"] >= order_price
                )
                if not (
                    placement <= event_ts <= placement + timedelta(seconds=passive_timeout_seconds)
                ):
                    continue
                if trade["side"] != wanted_trade_side or not crossed:
                    continue
                consumed = min(queue, trade["quantity"])
                queue -= consumed
                filled += min(10.0 - filled, trade["quantity"] - consumed)
                if filled:
                    fill_at = event_ts
                if filled == 10:
                    break
            if model != "passive_conservative" and filled < 10:
                for book in books:
                    event_ts = _ts(book["exchange_ts"])
                    if not (
                        placement
                        <= event_ts
                        <= placement + timedelta(seconds=passive_timeout_seconds)
                    ):
                        continue
                    executable = book["best_ask" if side == "LONG" else "best_bid"]
                    crossed = (
                        executable <= order_price if side == "LONG" else executable >= order_price
                    )
                    if not crossed:
                        continue
                    quantity = book["asks" if side == "LONG" else "bids"][0]["quantity"]
                    filled += min(10.0 - filled, quantity)
                    fill_at = event_ts
                    if filled == 10:
                        break
            status = "NO_FILL" if filled == 0 else ("FULL_FILL" if filled == 10 else "PARTIAL_FILL")
            executions[f"{side}/{model}"] = {
                "status": status,
                "filled": filled,
                "remaining": 10.0 - filled,
                "fill_price": order_price if filled else None,
                "delay_ms": int((fill_at - placement).total_seconds() * 1000) if fill_at else None,
            }
    result["executions"] = executions
    target = t0 + timedelta(seconds=10)
    target_book = max(
        (row for row in books if _ts(row["exchange_ts"]) <= target),
        key=lambda row: _ts(row["exchange_ts"]),
    )
    entry = float(data["feature"]["best_ask"])
    executable_path = [
        float(row["best_bid"]) for row in books if t0 <= _ts(row["exchange_ts"]) <= target
    ]
    result["ideal_long_10s"] = {
        "future_price": float(target_book["best_bid"]),
        "gross_pnl": (float(target_book["best_bid"]) - entry) * 10.0,
        "mfe_ticks": max(0.0, max(price - entry for price in executable_path)) / data["tick_size"],
        "mae_ticks": max(0.0, entry - min(executable_path)) / data["tick_size"],
    }
    return result


def _production_executions(rows: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {
        f"{row['side']}/{row['execution_model']}": {
            "status": row["fill_status"],
            "filled": row["filled_quantity"],
            "remaining": row["remaining_quantity"],
            "fill_price": row["fill_price"],
            "delay_ms": (
                int((row["fill_ts"] - row["order_ts"]).total_seconds() * 1000)
                if row["fill_ts"] is not None
                else None
            ),
        }
        for row in rows
    }


def _raw_tables(data: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    def stamp(row: dict[str, Any], event_id: str) -> dict[str, Any]:
        timestamp = _ts(row["exchange_ts"])
        return {
            **row,
            "event_id": event_id,
            "exchange_ts": timestamp,
            "receive_ts": timestamp,
            "processing_ts": timestamp,
            "materialized_ts": timestamp,
        }

    books = [stamp(row, f"book-{index:02d}") for index, row in enumerate(data["orderbook"])]
    trades = [
        stamp({**row, "aggressor_side": row["side"]}, f"trade-{index:02d}")
        for index, row in enumerate(data["trades"])
    ]
    lasts = [
        stamp({**row, "last_price": row["price"]}, f"last-{index:02d}")
        for index, row in enumerate(data["last_prices"])
    ]
    candles: dict[str, list[dict[str, Any]]] = {}
    for minutes in (1, 5, 15):
        rows = []
        for index, candle in enumerate(data["candles"]["complete"]):
            close = _ts(candle["close_ts"])
            rows.append(
                stamp(
                    {
                        **candle,
                        "exchange_ts": candle["close_ts"],
                        "candle_end": close,
                        "is_complete": True,
                    },
                    f"candle-{minutes}m-{index}",
                )
            )
        candles[f"candles_{minutes}m"] = rows
    status = stamp(
        {"exchange_ts": data["candidate_start"], "status": "NORMAL_TRADING"},
        "status-0",
    )
    return {
        "raw_orderbook": books,
        "raw_trades": trades,
        "raw_last_price": lasts,
        **candles,
        "market_status_events": [status],
    }


def test_golden_synthetic_production_oracle_and_manual_agree() -> None:
    data = json.loads(FIXTURE.read_text(encoding="utf-8"))
    expected = data["manual_expected"]
    oracle = _oracle(data, passive_timeout_seconds=5.0)
    raw = _raw_tables(data)
    result = RawOnlyPipeline(
        tick_size=data["tick_size"],
        feature_config=FeatureConfig(
            tick_size=data["tick_size"], required_book_levels=20, candle_warmup=1
        ),
        execution_config=ExecutionConfig(
            tick_size=data["tick_size"],
            order_quantity=10.0,
            aggressive_latency_ms=100,
            passive_timeout_ms=5_000,
        ),
    ).materialize(
        raw,
        candidate_start=_ts(data["candidate_start"]),
        candidate_end=_ts(data["candidate_start"]) + timedelta(milliseconds=1),
        materialized_ts=_ts(data["candidate_end"]) + timedelta(minutes=30),
    )
    feature = result.feature_snapshots[0]
    production = _production_executions(result.execution_simulations)

    assert 20 <= len(data["orderbook"]) <= 30
    assert 15 <= len(data["trades"]) <= 30
    assert {row["side"] for row in data["trades"]} == {"BUY", "SELL", "UNKNOWN"}
    assert oracle["trade_flow_10s"] == expected["trade_flow_10s"]
    assert feature["trade_flow_10s"] == expected["trade_flow_10s"]
    assert oracle["data_age_ms"] == expected["data_age_ms"]
    assert feature["last_trade_exchange_age_ms"] == 2000.0
    assert feature["bid_depth_20"] == expected["candidate_bid_depth_20"]
    assert feature["ask_depth_20"] == expected["candidate_ask_depth_20"]
    assert feature["imbalance_20"] == expected["candidate_imbalance_20"]
    oracle_v4 = {
        key.replace("/passive_best", "/passive_queue").replace(
            "/aggressive_marketable", "/aggressive"
        ): value
        for key, value in oracle["executions"].items()
        if not key.endswith("passive_conservative") and not key.endswith("passive_delayed")
    }
    for value in oracle_v4.values():
        value["status"] = value["status"].removesuffix("_FILL")
    for key, manual in expected["schema_v4_executions"].items():
        for field, value in manual.items():
            assert (
                oracle_v4[key][field] == pytest.approx(value)
                if isinstance(value, float)
                else oracle_v4[key][field] == value
            )
            assert (
                production[key][field] == pytest.approx(value)
                if isinstance(value, float)
                else production[key][field] == value
            )
        for field in manual:
            assert production[key][field] == pytest.approx(oracle_v4[key][field])

    complete_ids = [
        row["candle_id"]
        for row in data["candles"]["complete"]
        if row["close_ts"] <= data["candidate_start"]
    ]
    assert complete_ids == expected["eligible_candle_ids"]
    first_book = data["orderbook"][0]
    bid_depth = sum(level["quantity"] for level in first_book["bids"])
    ask_depth = sum(level["quantity"] for level in first_book["asks"])
    assert bid_depth == expected["top_bid_depth"]
    assert ask_depth == expected["top_ask_depth"]
    assert (bid_depth - ask_depth) / (bid_depth + ask_depth) == expected["top_imbalance"]

    ideal_long_id = next(
        row["simulation_id"]
        for row in result.execution_simulations
        if row["side"] == "LONG" and row["execution_model"] == "ideal_touch"
    )
    outcome = next(
        row
        for row in result.future_outcomes
        if row["simulation_id"] == ideal_long_id and row["horizon_seconds"] == 10
    )
    manual_outcome = expected["ideal_long_10s"]
    outcome_fields = {
        "future_price": "executable_exit_price",
        "gross_pnl": "gross_pnl",
        "mfe_ticks": "mfe_ticks",
        "mae_ticks": "mae_ticks",
    }
    for manual_field, production_field in outcome_fields.items():
        assert oracle["ideal_long_10s"][manual_field] == pytest.approx(manual_outcome[manual_field])
        assert outcome[production_field] == pytest.approx(manual_outcome[manual_field])
        assert outcome[production_field] == pytest.approx(oracle["ideal_long_10s"][manual_field])

    stops = result.shadow_stop_results
    exits = result.shadow_exit_results
    assert any(
        row["stop_triggered"] and row["executable_exit_price"] != row["stop_level"] for row in stops
    )
    assert {row["side"] for row in stops} == {"LONG", "SHORT"}
    assert len({(row["exit_model"], row["trigger_reason"]) for row in exits}) > 7
    oracle_tables = {
        **{name: pa.Table.from_pylist(rows) for name, rows in raw.items()},
        **{name: pa.Table.from_pylist(rows) for name, rows in result.tables.items()},
    }
    oracle_report = validate_independent_oracle(
        oracle_tables, tick_size=data["tick_size"], require_all_contracts=False
    )
    assert oracle_report["metrics"]["secrets"]["hits"] == 0
